### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by tstehr** [tstehr/RecipeMD#19]
The library and specification should have a license. I propose to license both under the [LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License).

All persons who have in the past contributed to this repository need to agree to this change. According to the [repository statistics](https://github.com/tstehr/RecipeMD/graphs/contributors) the contributors are:

- @AberDerBart 
- @dadada 
- @dasnessie  

Please comment below whether you agree to licensing your contribution to RecipeMD under the LGPL. I'd be happy to discuss licensing options or other concerns.

**Comment by dadada** [comment]
I would not mind publishing the specification under a more permissive license. Also LGPL is more of a software license. Some advantages of the Apache License, Version 2.0

- "patent free" guarantee
- grants no rights to trademarks

The license is very permissive and the GPL allows Apache licensed works to be included (but not the other way around).

Anyway, I'm really not set on this specific license so I'd like to hear your suggestions.

**Comment by dadada** [comment]
A popular example for open specificatons would be the [Matrix protocol](https://matrix.org/docs/spec/)

**Comment by tstehr** [comment]
Thanks for your quick response! Comments inline:

> I'd like to see the specification pubished under a more permissive license. 

1. For simplicity I'd like to add one license that applies to everything in the repository. 

2. Is there a specific reason you want a permissive license? I looked at [permissive] and 
    [copyleft] licenses (specifically MIT and GPL) and concluded that I'd prefer if derivative
    works were also open sourced, which is enforced by a copyleft license like GPL but not by 
    a permissive license.
    I propose LGPL because its [linking exception] allows non-GPL code (e.g. licensed under the
    Apache license) to use the library while maintaining the copyleft protection.

[permissive]: https://en.wikipedia.org/wiki/Permissive_software_license
[copyleft]: https://en.wikipedia.org/wiki/Copyleft
[linking exception]: https://en.wikipedia.org/wiki/GPL_linking_exception

> Also LGPL is more of a software license. Some advantages of the Apache License, Version 2.0

As far as I understand the Apache License is also a software license. [Its documentation] states the license is used "to distribute software and documentation". However both licenses can apply to documents just fine.
 
> - "patent free" guarantee
> - grants no rights to trademarks
> 
> The license is very permissive and the GPL allows Apache licensed works to be included (but not the other way around).

The compatibility of the Apache License with other License is due to its permissiveness which comes with the drawback that it allows proprietization. As stated above this is something that I'd like to avoid.

> Anyway, I'm really not set on this specific license so I'd like to hear your suggestions.

I'm not dogmatically set on copyleft license and open to arguments against it. If the consensus among contributors is that we should use a permissive license, I'd be find with that.

**Comment by dadada** [comment]
If you prefer a copyleft approach, I'm fine with that, I guess. The only open question I have would be if the linking exception applies to the specification: e.g. If a software is licensed under Apache 2.0 and implements the specification (LGPL), is this explicitly allowed by the LGPL?

**Comment by AberDerBart** [comment]
I root for having a seperate license for the specification to exclude any legal inaccuracies and complcations. I root for CC-BY-SA.

**Comment by tstehr** [comment]
@dadada I am not a lawyer, but according to some research I did it should be fine for other implementations to choose whatever license they want:

- https://opensource.stackexchange.com/q/8380
- https://opensource.stackexchange.com/q/7327

**Comment by dadada** [comment]
Ok. Then I vote LGPL.

**Comment by tstehr** [comment]
@AberDerBart As stated above I'd prefer to be able to say "everything in this repository is licensed under $LICENSE". In my opinion this would avoid complications and inaccuracies rather then create them.

To make licensing very clear, I'd include the license in a `LICENSE` file in the repository, and also add a license statement to the `README` and `specification.md`. By this the code and the license would in fact by licensed separately, but under the same license.

With regard to the license you propose CC BY-SA and LGPL are both [copyleft] licenses. As far as I understand their effect is very similar: 

[copyleft]: https://en.wikipedia.org/wiki/Copyleft

[![Screenshot 2019-12-15 at 18 47 54](https://user-images.githubusercontent.com/1938293/70867394-3475ee00-1f75-11ea-80ea-2dc2e2a95e7d.png)
Extracted from Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses)

If you still insist on CC BY-SA for the specification, how would you feel about the following compromise:

1. Everything in the repository (including code, documentation and assets) is licensed under LGPL
2. The specification is additionally [dual-licensed] under CC BY-SA. This allows creators of derivative works to choose between LGPL and CC BY-SA when creating the derivative work. The dual licensing would be stated similar to [this example](https://softwareengineering.stackexchange.com/a/318783) in the project's `README` and in `specification.md`. 

[dual-licensed]: https://en.wikipedia.org/wiki/Multi-licensing

**Comment by AberDerBart** [comment]
I see your point. I think LGPL is fine for me.

**Comment by dasnessie** [comment]
I'm happy with LGPL as well.
