### ISSUE TITLE
Meta-Recipes

### ISSUE THREAD

**Issue by tstehr** [tstehr/RecipeMD#2]
Recipes should have the the ability to use other recipes as Ingredients. I propose roughly the following syntax:

```
# Nachos

---

- 200g [Guacamole](guacamole.md)
- 200g [Refried Beans](refried_beans.md)
```

**Comment by timschubert** [comment]
You could use the same format for amounts as in recipes and URIs for included recipes (`path-rootless` in this case). This should also work great for creating menus.

```
# Example Menu

Some description.
Tags and amounts depend on recipes.

---

## Main course

- *4 l* [Kartoffeltopf](file:griechischer_kartoffeltopf.md)
- *1* [Brot](file:schwarzbierbrot.md)

## Dessert

- *40 l* Ice Cream

---

Text with description for the meta recipe and how to prepare it.
```

**Comment by timschubert** [comment]
The [common mark spec](https://spec.commonmark.org/0.28/#link-destination) does not specify a format for link targets, so this should probably be left unspecified. As you pointed out it should be enough to extend the syntax for ingredients to include [links with descriptions](https://spec.commonmark.org/0.28/#link-reference-definitions).
