### ISSUE TITLE
Indentation on recipemd.org

### ISSUE THREAD

**Issue by dasnessie** [tstehr/RecipeMD#22]
On mobile, the indentation for bulleted lists on recipemd.org looks very weird. I feel that the bulleted lists should be at the same indentation level as the numbered lists. 
Here's a quick screenshot I took: 

![Screenshot_20200307-132246_Firefox](https://user-images.githubusercontent.com/43586524/76143373-37b1df00-6077-11ea-90bb-2e5629b4ea53.png)

**Comment by tstehr** [comment]
Thanks for the report, I just fixed it!
